name: Release
on:
  push:
  release:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install the dependencies
        run: npm i

      - name: Install vsce
        run: npm i -g vsce

      - name: Package & Publish
        run: vsce package && vsce publish --pat $VSCE_PAT

      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
